org: samartharoraa
app: test-app
service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  
functions:
  api:
    handler: index.handler
    events:
      - http: 
          path: /path
          method: ANY
          cors: true
      - httpApi: '*'
     
        
    timeout: 900
    environment:
      OPENAI_API_KEY: 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